title: Flow & Interaction Group
description: Accessibility, cognition, and interaction design research.
url: https://flow-and-interaction.org
baseurl: ""  # change if you publish under a subpath
permalink: pretty
markdown: kramdown
highlighter: rouge

collections:
  themes:
    output: true
    permalink: /themes/:slug/
  publications:
    output: true
    permalink: /publications/:slug/
  people:
    output: true
    permalink: /people/:slug/
  projects:
    output: true
    permalink: /projects/:slug/
  podcasts:
    output: true
    permalink: /media/podcasts/:slug/
  videos:
    output: true
    permalink: /media/videos/:slug/

defaults:
  - scope: { path: "assets/transcripts" }
    values: { layout: transcript }
  - scope: { path: "", type: "posts" }
    values: { layout: post }
  - scope: { path: "", type: "themes" }
    values: { layout: theme }
  - scope: { path: "", type: "publications" }
    values: { layout: publication }
  - scope: { path: "" }
    values: { layout: default }
  - scope: { path: "", type: "podcasts" }
    values: { layout: podcast }
  - scope: { path: "", type: "videos" }
    values: { layout: video }
  - scope: { path: "", type: "projects" }
    values: { layout: project }

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

feed:
  path: feed.xml

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
excerpt_separator: "<!--more-->"
